### ISSUE TITLE
Build failed: iolStateMachineHandler

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/iol#23] opened 2016-04-06 11:22 UTC
Hello, I have a problem compiling `iol`.
This is what I get (on several different machines): 

> icub@console1:/mnt/data/Data/robot/icub-contrib-iit/iol/build$ make -j6
Copying /mnt/data/Data/robot/icub-contrib-iit/iol/app/lua/iol_main.lua to /mnt/data/Data/robot/icub-contrib-iit/iol/build/bin/./
[  8%] [ 16%] Built target blobSelector
Built target iolHelper
[ 41%] [ 41%] Built target himrepClassifier
[ 50%] [ 66%] [ 75%] [ 91%] Built target iolReachingCalibration
Built target copy_lua_in_build
Building CXX object src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/module.cpp.o
Building CXX object src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/utils.cpp.o
Building CXX object src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/main.cpp.o
Copying /mnt/data/Data/robot/icub-contrib-iit/iol/app/lua/mobile/iol_main_mobile.lua to /mnt/data/Data/robot/icub-contrib-iit/iol/build/bin/./
[ 91%] Built target copy_lua_mb_in_build
In file included from /mnt/data/Data/robot/icub-contrib-iit/iol/src/iolStateMachineHandler/src/utils.cpp:21:0:
/mnt/data/Data/robot/icub-contrib-iit/iol/src/iolStateMachineHandler/include/module.h:183:57: error: could not convert ‘yarp::sig::Vector(3ul, (* &0.0))’ from ‘yarp::sig::Vector’ to ‘yarp::sig::Vector&’
                                   Vector &y=Vector(3,0.0), const Bottle &blobs=Bottle(),const int iBlob=RET_INVALID);
                                                         ^
In file included from /mnt/data/Data/robot/icub-contrib-iit/iol/src/iolStateMachineHandler/src/main.cpp:263:0:
/mnt/data/Data/robot/icub-contrib-iit/iol/src/iolStateMachineHandler/include/module.h:183:57: error: could not convert ‘yarp::sig::Vector(3ul, (* &0.0))’ from ‘yarp::sig::Vector’ to ‘yarp::sig::Vector&’
                                   Vector &y=Vector(3,0.0), const Bottle &blobs=Bottle(),const int iBlob=RET_INVALID);
                                                         ^
In file included from /mnt/data/Data/robot/icub-contrib-iit/iol/src/iolStateMachineHandler/src/module.cpp:26:0:
/mnt/data/Data/robot/icub-contrib-iit/iol/src/iolStateMachineHandler/include/module.h:183:57: error: could not convert ‘yarp::sig::Vector(3ul, (* &0.0))’ from ‘yarp::sig::Vector’ to ‘yarp::sig::Vector&’
                                   Vector &y=Vector(3,0.0), const Bottle &blobs=Bottle(),const int iBlob=RET_INVALID);
                                                         ^
src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/build.make:54: recipe for target 'src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/utils.cpp.o' failed
make[2]: *** [src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/utils.cpp.o] Error 1
make[2]: *** Attente des tâches non terminées....
src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/build.make:123: recipe for target 'src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/main.cpp.o' failed
make[2]: *** [src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/main.cpp.o] Error 1
src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/build.make:100: recipe for target 'src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/module.cpp.o' failed
make[2]: *** [src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/src/module.cpp.o] Error 1
CMakeFiles/Makefile2:238: recipe for target 'src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/all' failed
make[1]: *** [src/iolStateMachineHandler/CMakeFiles/iolStateMachineHandler.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Could it come from lua not up to date?

**Comment by Tobias-Fischer** [comment] 2016-04-06 11:32
I can confirm that the build fails here as well. It is not due to LUA, but because of a wrong initialization of a reference introduced in https://github.com/robotology/iol/commit/34c503e689d7a70dc40156076f74ee5fc573a0eb

I'm sure @pattacini can fix it in less than two minutes :package: 

Best, Tobi

**Comment by pattacini** [comment] 2016-04-06 11:49
Should bi fixed via 25fde268b9d6c3005434526044532619404ffba5.
@gregoire-pointeau thanks for spotting
@Tobias-Fischer I've been almost within 2 mins :smirk:

**Closed by pattacini** 2016-04-06 11:49 UTC
